### PR TITLE
Enhancement and Bug Fixes. #29 #31, #32, #34

### LINKED ISSUE #29: Enhancement: Banner and Logo Upload
Don't need to click Upload to upload the image to storage.

Screenshot 2023-09-03 at 7 46 12 PM

### LINKED ISSUE #31: Bug: Upload of image improvements
What if I don't want to continue with the adding of team but the banner and logo has already been uploaded?

How it can be resolved: 

- No button for upload of image.
- Use an array for logo and banner preview.
- Image will only be uploaded to storage once the user clicks Add button.

Screenshot 2023-09-03 at 7 51 07 PM

### LINKED ISSUE #32: Bug: Adding of teams not refreshed
How can this be solved:

- When the user adds a new team the modal should be closed.
- Query should mutate to refresh the list of teams.

Screenshot 2023-09-03 at 7 54 45 PM

### LINKED ISSUE #34: Bug: Team delete
The team delete won't be deleted asap. You need to click it twice or 3 times for it to delete the document and the image on the storage. 

How can be fixed:

- await functionality -> the page will only notify/ refresh the page once the image and the document has been successfully deleted

### PR DESCRIPTION
**Pull request by tylerbert31**
Added ImageUploadService, Fixed DeleteImage Bug, Added DeleteTeam Confirmation

image

image

image

image

### CODE REVIEW

File: src/service/imageUploadService.jsx [hunk 1]
```diff
@@ -0,0 +1,48 @@
+import { useState } from "react";
+import { ref, uploadBytes, getDownloadURL } from "firebase/storage";
+import { storage } from "../../firebase";
+import { v4 } from "uuid";
+
+const UploadHandler = () => {
+  const [bannerFile, setBannerFile] = useState(null);
+  const [logoFile, setLogoFile] = useState(null);
+  const [uploading, setUploading] = useState(false);
```
Comment (mgacrama211176) [inline src/service/imageUploadService.jsx]: Ty can we transfer this kung asa ni siya g.gamit? Wala mani siya g.gamit dri nga service man gud. 
and need ta ani nga service kay ang path which is kung asa siya e.save and unsay name sa file. We can refer sa DeleteImageService as a logic.

File: src/Views/Admin/Teams/Addteam/AdTeam.jsx [hunk 2]
```diff
@@ -32,36 +31,43 @@ const AdTeam = () => {
...
-  const handleImageUpload = (event) => {
+  const {
+    uploadFile2,
+    logoFile,
+    setLogoFile,
+    bannerFile,
+    setBannerFile,
+    uploading,
+    setUploading,
+  } = UploadHandler();
```
Comment (mgacrama211176) [inline src/Views/Admin/Teams/Addteam/AdTeam.jsx]: Let's try to avoid deconstructing unneeded variables. 

We can just call UploadHandler(path, fileName);

only these parameters are need by the uploadHandlerService.

**Review by mgacrama211176 — CHANGES_REQUESTED** [review]
Minor changes nlang ty. Overall well done. 👍

File: src/service/imageUploadService.jsx (hunk 1 above)
Comment (tylerbert31) [reply src/service/imageUploadService.jsx:9]: image

Comment (tylerbert31) [reply src/service/imageUploadService.jsx]: image

File: src/Views/Admin/Teams/Addteam/AdTeam.jsx (hunk 2 above)
Comment (tylerbert31) [reply src/Views/Admin/Teams/Addteam/AdTeam.jsx]: image

**Review by mgacrama211176 — APPROVED** [review]
